version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsul-feedback-bot
    restart: always
    volumes:
      - ./bot.js:/app/bot.js
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Tashkent
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50M'
        reservations:
          memory: '20M'
